summon projectile:boiling_bubble ~~~0.5
summon projectile:boiling_bubble ~~~-0.5
summon projectile:boiling_bubble ~0.5~~
summon projectile:boiling_bubble ~-0.5~~
summon projectile:boiling_bubble ~0.5~~0.5
summon projectile:boiling_bubble ~-0.5~~-0.5
summon projectile:boiling_bubble ~0.5~~-0.5
summon projectile:boiling_bubble ~-0.5~~0.5
summon projectile:boiling_bubble ~~~
summon projectile:boiling_bubble ~~0.5~0.5
summon projectile:boiling_bubble ~~0.5~-0.5
summon projectile:boiling_bubble ~0.5~0.5~
summon projectile:boiling_bubble ~-0.5~0.5~
summon projectile:boiling_bubble ~0.5~0.5~0.5
summon projectile:boiling_bubble ~-0.5~0.5~-0.5
summon projectile:boiling_bubble ~0.5~0.5~-0.5
summon projectile:boiling_bubble ~-0.5~0.5~0.5
summon projectile:boiling_bubble ~~0.5~
summon projectile:boiling_bubble ~~-0.5~0.5
summon projectile:boiling_bubble ~~-0.5~-0.5
summon projectile:boiling_bubble ~0.5~-0.5~
summon projectile:boiling_bubble ~-0.5~-0.5~
summon projectile:boiling_bubble ~0.5~-0.5~0.5
summon projectile:boiling_bubble ~-0.5~-0.5~-0.5
summon projectile:boiling_bubble ~0.5~-0.5~-0.5
summon projectile:boiling_bubble ~-0.5~-0.5~0.5
summon projectile:boiling_bubble ~~-0.5~
summon projectile:boiling_bubble ~~~1.5
summon projectile:boiling_bubble ~~~-1.5
summon projectile:boiling_bubble ~1.5~~
summon projectile:boiling_bubble ~-1.5~~
summon projectile:boiling_bubble ~1.5~~1.5
summon projectile:boiling_bubble ~-1.5~~-1.5
summon projectile:boiling_bubble ~1.5~~-1.5
summon projectile:boiling_bubble ~-1.5~~1.5
summon projectile:boiling_bubble ~~1.5~1.5
summon projectile:boiling_bubble ~~1.5~-1.5
summon projectile:boiling_bubble ~1.5~1.5~
summon projectile:boiling_bubble ~-1.5~1.5~
summon projectile:boiling_bubble ~1.5~1.5~1.5
summon projectile:boiling_bubble ~-1.5~1.5~-1.5
summon projectile:boiling_bubble ~1.5~1.5~-1.5
summon projectile:boiling_bubble ~-1.5~1.5~1.5
summon projectile:boiling_bubble ~~1.5~
summon projectile:boiling_bubble ~~-1.5~1.5
summon projectile:boiling_bubble ~~-1.5~-1.5
summon projectile:boiling_bubble ~1.5~-1.5~
summon projectile:boiling_bubble ~-1.5~-1.5~
summon projectile:boiling_bubble ~~-1.5~
summon projectile:boiling_bubble ~~~1
summon projectile:boiling_bubble ~~~-1
summon projectile:boiling_bubble ~1~~
summon projectile:boiling_bubble ~-1~~
summon projectile:boiling_bubble ~1~~1
summon projectile:boiling_bubble ~-1~~-1
summon projectile:boiling_bubble ~1~~-1
summon projectile:boiling_bubble ~-1~~1
summon projectile:boiling_bubble ~~~
summon projectile:boiling_bubble ~~1~1
summon projectile:boiling_bubble ~~1~-1
summon projectile:boiling_bubble ~1~1~
summon projectile:boiling_bubble ~-1~1~
summon projectile:boiling_bubble ~1~1~1
summon projectile:boiling_bubble ~-1~1~-1
summon projectile:boiling_bubble ~1~1~-1
summon projectile:boiling_bubble ~-1~1~1
summon projectile:boiling_bubble ~~1~
summon projectile:boiling_bubble ~~-1~1
summon projectile:boiling_bubble ~~-1~-1
summon projectile:boiling_bubble ~1~-1~
summon projectile:boiling_bubble ~-1~-1~
summon projectile:boiling_bubble ~~-1~