summon projectile:primordial_homing_fireball ^^^9
summon projectile:primordial_homing_fireball ^9^^9
summon projectile:primordial_homing_fireball ^-9^^9
summon projectile:primordial_homing_fireball ^^9^9
summon projectile:primordial_homing_fireball ^^-9^9
summon projectile:primordial_homing_fireball ^-9^-9^9
summon projectile:primordial_homing_fireball ^9^9^9
summon projectile:primordial_homing_fireball ^-9^9^9
summon projectile:primordial_homing_fireball ^9^-9^9
summon projectile:primordial_homing_fireball ^^^15
summon projectile:primordial_homing_fireball ^15^^15
summon projectile:primordial_homing_fireball ^-15^^15
summon projectile:primordial_homing_fireball ^^15^15
summon projectile:primordial_homing_fireball ^^-15^15
summon projectile:primordial_homing_fireball ^-15^-15^15
summon projectile:primordial_homing_fireball ^15^15^15
summon projectile:primordial_homing_fireball ^-15^15^15
summon projectile:primordial_homing_fireball ^15^-15^15
summon projectile:primordial_homing_fireball ^^^3
summon projectile:primordial_homing_fireball ^3^^3
summon projectile:primordial_homing_fireball ^-3^^3
summon projectile:primordial_homing_fireball ^^3^3
summon projectile:primordial_homing_fireball ^^-3^3
summon projectile:primordial_homing_fireball ^-3^-3^3
summon projectile:primordial_homing_fireball ^3^3^3
summon projectile:primordial_homing_fireball ^-3^3^3
summon projectile:primordial_homing_fireball ^3^-3^3