summon projectile:prismarine_blast ^^^2.5
summon projectile:prismarine_blast ^^^3
summon projectile:prismarine_blast ^^^3.5
summon projectile:prismarine_blast ^^^4
summon projectile:prismarine_blast ^^^4.5
summon projectile:prismarine_blast ^^^5
summon projectile:prismarine_blast ^^^5.5
summon projectile:prismarine_blast ^^^6
summon projectile:prismarine_blast ^^^6.5
summon projectile:prismarine_blast ^^^7
summon projectile:prismarine_blast ^^^7.5
summon projectile:prismarine_blast ^^^8
summon projectile:prismarine_blast ^^^8.5
summon projectile:prismarine_blast ^^^9
summon projectile:prismarine_blast ^^^9.5
summon projectile:prismarine_blast ^^^10
summon projectile:prismarine_blast ^^^10.5
summon projectile:prismarine_blast ^^^11
summon projectile:prismarine_blast ^^^11.5
summon projectile:prismarine_blast ^^^12
summon projectile:prismarine_blast ^^^12.5
summon projectile:prismarine_blast ^^^13
summon projectile:prismarine_blast ^^^13.5
summon projectile:prismarine_blast ^^^14
summon projectile:prismarine_blast ^^^14.5
summon projectile:prismarine_blast ^^^15
summon projectile:prismarine_blast ^^^15.5
summon projectile:prismarine_blast ^^^16
summon projectile:prismarine_blast ^^^16.5
summon projectile:prismarine_blast ^^^17
summon projectile:prismarine_blast ^^^17.5
summon projectile:prismarine_blast ^^^18
summon projectile:prismarine_blast ^^^18.5
summon projectile:prismarine_blast ^^^19
summon projectile:prismarine_blast ^^^19.5
summon projectile:prismarine_blast ^^^20
summon projectile:prismarine_blast ^^^20.5
summon projectile:prismarine_blast ^^^21
summon projectile:prismarine_blast ^^^21.5
summon projectile:prismarine_blast ^^^22
summon projectile:prismarine_blast ^^^22.5
summon projectile:prismarine_blast ^^^23
summon projectile:prismarine_blast ^^^23.5
summon projectile:prismarine_blast ^^^24
summon projectile:prismarine_blast ^^^24.5